Draft of Report
========================================================
By Abhishek Chakraborty

I have obtained the data from www.espnsoccernet.com for the players at their national level performances as well their performances for their clubs(includes clubs playing in the leagues of England, Germany, Italy and Spain).I have segmented the players into Goalkeepers and Outfield players.This is because the statistics(columns) for the goalkeepers and the outfield players are different.
Then I have merged the datasets to obtain statistics for each player at their national level as well as club level.

```{r}
library(XML)
library(plyr)
library(ggplot2)

# Information(id's) of each club playing at each of the above mentioned leagues.We need the id's to get the data for each club,since id is the unique element that denotes a particular club in the website.
clubs <- read.csv("club teams.csv")
dim(clubs)  # There are 20 clubs in each of English,Italian and Spanish leagues and 18 in German league.
head(clubs)
# Id's for the national teams participating in World Cup 2014.
nations <- read.csv("national teams.csv")
head(nations) 

# Extracting the data for players of all nations participating in 2014 World Cup
nat_goalie <- nat_player <- NULL
for(i in nations$id)
{
  url <- paste("http://espnfc.com/team/squad/_/id/",i,"/season/2013/league/all/brazil?cc=5901",sep="")
  table <- readHTMLTable(url)
  goalie <- table[[1]]
  players <- table[[2]]
  nat_goalie <- rbind(nat_goalie,data.frame(goalie, National.Teams = nations$National.Teams[nations$id == i]))   #  Goalkeeping statistics
  nat_player <- rbind(nat_player,data.frame(players, National.Teams = nations$National.Teams[nations$id == i]))   # Statistics for Outfield players
}

nat_player$G <- as.numeric(as.character(nat_player$G))  
nat_player$GS <- as.numeric(as.character(nat_player$GS))
nat_player$SB <- as.numeric(as.character(nat_player$SB))

n.Goals <- ddply(nat_player, .(National.Teams), summarize, Goals.per.match = sum(G)/max(GS + SB), Total.Goals = sum(G))

# Extracting the data for players of all clubs that are part of the English,German,Italian and Spanish leagues.
club_goalie <- club_player <- NULL
for(i in clubs$id)
{
  url <- paste("http://espnfc.com/team/squad/_/id/",i,"/season/2013/league/all/manchester-united?cc=5901",sep="")
  table <- readHTMLTable(url)
  cgoalie <- table[[1]]
  cplayers <- table[[2]]
  club_goalie <- rbind(club_goalie, data.frame(cgoalie, Teams = clubs$Teams[clubs$id == i], League = clubs$League[clubs$id == i]))   # Goalkeeping statistics
  club_player <- rbind(club_player,data.frame(cplayers, Teams = clubs$Teams[clubs$id == i], League = clubs$League[clubs$id == i]))   # Statistics for Outfield players
}

goalie <- merge(nat_goalie, club_goalie, by = "NAME")
head(goalie)
player <- merge(nat_player, club_player, by = "NAME")
head(player)

# .x denotes the performances for the national teams and .y for the clubs
player$G.x <- as.numeric(as.character(player$G.x))
player$G.y <- as.numeric(as.character(player$G.y))
player$GS.x <- as.numeric(as.character(player$GS.x))
player$SB.x <- as.numeric(as.character(player$SB.x))
player$GS.y <- as.numeric(as.character(player$GS.y))
player$SB.y <- as.numeric(as.character(player$SB.y))

Goals <- ddply(player, .(National.Teams), summarize, sum.N.G = sum(G.x)/max(GS.x + SB.x), sum.C.G = sum(G.y)/max(GS.y + SB.y))

# I was just exploring the dataset.
# I would be looking at information somewhat similar to the plot below.
# This plots the goals per match of each team playing in 2014 edition in the past season(2013/14).It helps us to determine the kind of striking form that team is in going into the World cup.
qplot(x = reorder(National.Teams, Goals.per.match, sum), weight = Goals.per.match, data = n.Goals, geom = "bar", ylab = "Goals per Match", xlab = "Teams") + coord_flip()
```
One of the problems still needed to be fixed is the occurrence of some players more than once,since they have played for more than one club in the past season.
I intend to construct a statistic for each player that will predict the impact he is possibly going to have in the World cup for his national team.This statistic will take into account the statistics denoting his performances for the club and national team in the past season.
I also plan to look a bit into some exploratory data analysis for the data we have at hand,like looking into the no. of goals per individual per match,no. of assissts,no. of fouls conceded etc. that will indicate how is the team or the player going to perform at 2014 World Cup.